### ISSUE TITLE
What about caching?

### ISSUE THREAD

**Issue by BingeCode** [simonwep/vite-plugin-optimize-css-modules#5]
One of the advantages of vite's SHAs is that they remain unchanged if the file contents remain unchanged after building the project. This means that no matter how many times you build and deploy, users will not have to re-download files that they have in their cache already.

On the other hand this means that using your plugin, users might not re-download certain files that could have changed if they have them cached already since the identifier (the css class name) did not change as well.
Am I mistaken in that?

**Comment by simonwep** [comment]
> One of the advantages of vite's SHAs is that they remain unchanged if the file contents remain unchanged after building the project.

This module is only about minifying the _classname_, not the _filename_ (or name of the chunk) which might be cached by the browser/service worker. Not to mention that the generator doesn't generate these variables randomly, building your app twice should result in the same css files (and therefore names/hashes). Or what exactly do you mean with "if the file contents remain unchanged"?

**Comment by BingeCode** [comment]
Yeah I got confused there, my bad. Thanks for clarifying!
