### ISSUE TITLE
Default dictionary could be larger with some extra conditions

### ISSUE THREAD

**Issue by anton7r** [simonwep/vite-plugin-optimize-css-modules#6]
The default dictionary could have eleven additional characters `-0123456789`. all though special rules apply to them such as a number could not be the first character and  class name `-2` is not valid while `-a` and `--2` are valid. The code should just skip over the invalid cases but making that could be a bit difficult and would require tests to be written.

https://www.geeksforgeeks.org/which-characters-are-valid-in-css-class-names-selectors/

I'd be interested to hear thoughts on them. This seems to be similar to what was discussed in #1

**Comment by simonwep** [comment]
Great idea! I'll have a look into it :)
